/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AMFUser service. Represents a row in the &quot;user_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.amf.registration.model.impl.AMFUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.amf.registration.model.impl.AMFUserImpl}.
 * </p>
 *
 * @author Sara Liu
 * @see AMFUser
 * @see com.amf.registration.model.impl.AMFUserImpl
 * @see com.amf.registration.model.impl.AMFUserModelImpl
 * @generated
 */
public interface AMFUserModel extends BaseModel<AMFUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a a m f user model instance should use the {@link AMFUser} interface instead.
	 */

	/**
	 * Returns the primary key of this a m f user.
	 *
	 * @return the primary key of this a m f user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this a m f user.
	 *
	 * @param primaryKey the primary key of this a m f user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this a m f user.
	 *
	 * @return the user ID of this a m f user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this a m f user.
	 *
	 * @param userId the user ID of this a m f user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this a m f user.
	 *
	 * @return the user uuid of this a m f user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this a m f user.
	 *
	 * @param userUuid the user uuid of this a m f user
	 */
	public void setUserUuid(String userUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AMFUser amfUser);

	public int hashCode();

	public CacheModel<AMFUser> toCacheModel();

	public AMFUser toEscapedModel();

	public AMFUser toUnescapedModel();

	public String toString();

	public String toXmlString();
}