/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventMonitor service. Represents a row in the &quot;Registration_EventMonitor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.amf.registration.model.impl.EventMonitorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.amf.registration.model.impl.EventMonitorImpl}.
 * </p>
 *
 * @author Sara Liu
 * @see EventMonitor
 * @see com.amf.registration.model.impl.EventMonitorImpl
 * @see com.amf.registration.model.impl.EventMonitorModelImpl
 * @generated
 */
public interface EventMonitorModel extends BaseModel<EventMonitor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event monitor model instance should use the {@link EventMonitor} interface instead.
	 */

	/**
	 * Returns the primary key of this event monitor.
	 *
	 * @return the primary key of this event monitor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event monitor.
	 *
	 * @param primaryKey the primary key of this event monitor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event monitor ID of this event monitor.
	 *
	 * @return the event monitor ID of this event monitor
	 */
	public long getEventMonitorId();

	/**
	 * Sets the event monitor ID of this event monitor.
	 *
	 * @param eventMonitorId the event monitor ID of this event monitor
	 */
	public void setEventMonitorId(long eventMonitorId);

	/**
	 * Returns the company ID of this event monitor.
	 *
	 * @return the company ID of this event monitor
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this event monitor.
	 *
	 * @param companyId the company ID of this event monitor
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event monitor.
	 *
	 * @return the user ID of this event monitor
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this event monitor.
	 *
	 * @param userId the user ID of this event monitor
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event monitor.
	 *
	 * @return the user uuid of this event monitor
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this event monitor.
	 *
	 * @param userUuid the user uuid of this event monitor
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this event monitor.
	 *
	 * @return the user name of this event monitor
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this event monitor.
	 *
	 * @param userName the user name of this event monitor
	 */
	public void setUserName(String userName);

	/**
	 * Returns the start date of this event monitor.
	 *
	 * @return the start date of this event monitor
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this event monitor.
	 *
	 * @param startDate the start date of this event monitor
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the event type of this event monitor.
	 *
	 * @return the event type of this event monitor
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this event monitor.
	 *
	 * @param eventType the event type of this event monitor
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the ip address of this event monitor.
	 *
	 * @return the ip address of this event monitor
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this event monitor.
	 *
	 * @param ipAddress the ip address of this event monitor
	 */
	public void setIpAddress(String ipAddress);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(EventMonitor eventMonitor);

	public int hashCode();

	public CacheModel<EventMonitor> toCacheModel();

	public EventMonitor toEscapedModel();

	public EventMonitor toUnescapedModel();

	public String toString();

	public String toXmlString();
}